[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gumbel-mcts"
version = "0.2.0"
readme = "README.md"
description = "A lightweight, standalone, and modular Gumbel MCTS implementation"
license = "MIT"
requires-python = ">=3.10"
authors = [
    {name = "Olivier Koch", email = "olivier.koch@gmail.com"},
]
dependencies = [
    "numpy",
    "torch",
    "numba",
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
demo = [
    "matplotlib",
    "pillow",
    "gymnasium",
    "gym-pusht",
    "pymunk<7",
    "wandb",
]

[[tool.uv.index]]
url = "https://socket-registry.mistralai.com/pypi/simple/"
default = true

[project.urls]
Homepage = "https://github.com/olivkoch/gumbel-mcts"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
